apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  selector:
    app: user-app-label # Selector to match labels for selecting pods to expose
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
